### ISSUE TITLE
Waapi Transfer Error everytime when opening Reaper

### ISSUE THREAD

**Issue by 222emilia222** [karltechno/Reaper-Waapi-Transfer#19]
![image](https://user-images.githubusercontent.com/74257676/101300631-7a872a00-3836-11eb-8314-bdb8fa8c314b.png)
So this error shows up everytime I open Reaper after installing the extension. It happens regardless of wether Wwise is even open in the background or not. My Wwise version is supported and I allowed the Wwise Authoring API. 

The funny thing is everything works flawlessly. I just really hate the error message everytime and the obnoxious sound it makes. Is there any known way to fix this problem?

**Comment by jaku5** [comment]
I have the same error and it's also working perfectly other than that. Probably not be the answer you're looking for but I ended up disabling Windows system sounds to avoid that error sound :D

**Comment by karltechno** [comment]
Hi,

This is fixed in 6caa19f090b5028676ef9660581ebf88eca81b28 - although the last released binary doesn't have this commit.

As a workaround if you open Wwise, go into preferences and disable Waapi, close Wwise, open it again and enable then this should stop appearing. 

I'll try and build an updated binary at some point but I'm not actively maintaining this project right now.

**Comment by 222emilia222** [comment]
Thank you that fixed the problem! Im about to make a tutorial about your extension, as i really like it and i didnt want this ugly error message to take away from the shine. You are doing great work!!
